
#Texto a ser tokenizado
def criaTexto():
    return '''No coração de uma pequena vila costeira, onde o tempo parecia se arrastar com a lentidão de um rio preguiçoso, havia uma antiga livraria que encantava a todos que passavam por ali. O estabelecimento, chamado "Entre Páginas e Marés", era conhecido não apenas por sua vasta coleção de livros, mas também por seu ambiente acolhedor e misterioso. As paredes estavam revestidas com prateleiras de madeira escura, e o aroma de papel envelhecido misturava-se com o frescor do mar, criando uma atmosfera única e cativante.

Os moradores da vila, sempre curiosos e apaixonados por histórias, frequentavam a livraria com frequência. A proprietária, Dona Clara, era uma mulher de cabelos grisalhos e olhos brilhantes, cujo amor pelos livros era tão grande quanto sua habilidade em contar histórias. Ela conhecia cada livro da loja como se fossem velhos amigos e estava sempre disposta a recomendar a leitura perfeita para cada visitante.

Certa manhã, um jovem chamado Lucas entrou na livraria com um olhar de inquietação. Ele estava à procura de um livro específico, um manuscrito antigo que, segundo a lenda, continha segredos sobre o passado da vila. Dona Clara, com seu olhar sagaz, percebeu a determinação no rosto do jovem e começou a pesquisar nas prateleiras mais escondidas e empoeiradas. Depois de algum tempo, ela encontrou o que parecia ser o manuscrito procurado.

O livro estava coberto por uma camada de poeira, mas ao ser aberto, revelou páginas amareladas e manuscritos escritos com uma caligrafia elegante e misteriosa. Lucas ficou encantado e, com a ajuda de Dona Clara, começou a desvendar os segredos ocultos nas páginas. À medida que mergulhava na leitura, ele descobriu histórias de piratas, tesouros escondidos e eventos que moldaram a história da vila. Cada página revelava um pedaço do quebra-cabeça que, juntos, formavam uma história fascinante e surpreendente.

Com o tempo, Lucas não apenas desvendou os mistérios do livro, mas também se apaixonou pela vila e pela sua gente. Ele decidiu ficar e ajudar Dona Clara na livraria, contribuindo com suas descobertas e compartilhando o amor pela leitura com todos os que passavam pela pequena loja. A livraria "Entre Páginas e Marés" continuou a ser um lugar mágico, onde histórias ganhavam vida e novas aventuras eram constantemente escritas.'''